### PR TITLE
Blogs page and Blog posts

### PR DESCRIPTION
**Pull request by FaithDaka**
#### What does this PR do?
- Features the implementation for blogs and blog posts

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* git checkout main
* git pull origin main
* git checkout origin/ft-blogs
* yarn install
* yarn start
* import blog_posts data into admin dashboard
* route to the _News_ tab on the navbar to view blogs

#### What are the relevant tickets?
- None

#### Screenshots 
Screenshot (16)

Screenshot (18)

### CODE REVIEW

**Review by chrismclarke — CHANGES_REQUESTED** [review]
Many thanks @FaithDaka 
Great to see both the list page and individual post routing working well. 
I really appreciate the addition of the social sharing library and buttons also. 

My only minor (blocking) request will be to remove the additional depencies added for  `@emotion/react` and `@mui/material`. I can't see them used in the code, and so assume this was just for testing (?)

It would also be great when you have a chance to review #84 which introduces these libraries

**Comment by FaithDaka** [comment]
Thanks for the review @chrismclarke 

For the additional dependencies, those are peer dependencies for the MUI icon library as seen from their documentation.

> The @mui/icons-material package depends on @mui/material, which requires Emotion packages.
 If you don't use Material UI in your project yet, install the icons package with npm install @mui/icons-material @mui/material @emotion/styled @emotion/react.
See the [Installation](https://mui.com/material-ui/getting-started/installation/) page for additional docs about how to make sure everything is set up correctly.

I used the library for an icon on the blog post card. So should I switch to _react-icons_ library for icons?

**Comment by chrismclarke** [comment]
Oh, that makes sense although a little bit messy with the way we have to manually add the extra dependencies. Maybe it would be better to use: https://react-icons.github.io/

It has the full list of material icons (with various others), and I think might be easier to use. But no reason that should block this PR then, so I'll merge for now and we can leave as a follow-up item

**Review by chrismclarke — APPROVED** [review]

**Comment by FaithDaka** [comment]
Yeah, I should probably switch to _react-icons_ if it's less messy.

**Pull request merged**
